**Types of text classification**
- Binary
- Multi-Class
- Multi-Label

**Application**
- Email spam classification
- Customer Support
- Sentiment Analysis
- Language Detection
- Fake news detection

**The Pipeline**
- Data Aquisition
- Text Pre-processing
- Text Vectorization (eg. bag of words , TF-IDF , Word2Vec)
- Modelling (ML->Naive Bayes or DL->RNN,CNN,BERT)
- Evaluation (eg. accuracy , confusion matrix, f1-score)
- Deploy (eg. aws , streamlit)

**Different approach of text classification**
- Heuristic Approach:
- API's Approach:
    - AWS
- ML Approach:
    - At text vectorization stage
      - Bag of Words
      - n-Grams
      - TF-IDF
    - At modelling stage
      - Naive Bayes
      - SVM
      - Random Forest
- DL Approach:
  - RNN (LSTM)
  - CNN
  - BERT (Pre-trained model)

# **Machine Learning Approach**

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving IMDB Dataset.csv to IMDB Dataset.csv


In [3]:
temp_df = pd.read_csv('IMDB Dataset.csv')

In [5]:
df = temp_df.iloc[:10000]
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

**Apply pre-processing**

In [7]:
df['sentiment'].value_counts()

positive    5028
negative    4972
Name: sentiment, dtype: int64

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.duplicated().sum()

17

In [10]:
df.drop_duplicates(inplace=True)

<ipython-input-10-16cdb8520be8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [11]:
df.duplicated().sum()

0

In [12]:
# Basic Preprocessing
# Remove tags
# lowercase
# remove stopwords

In [13]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [14]:
df['review'] = df['review'].apply(remove_tags)

<ipython-input-14-00e93c2a3043>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [15]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [16]:
df['review'] = df['review'].apply(lambda x:x.lower())

<ipython-input-16-afca29351ee0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [18]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
<ipython-input-18-1b6c5daf96b7>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [19]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [20]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [21]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [22]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [23]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [24]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [26]:
X_train.shape

(7986, 1)

## **1. Bag of Words**

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
cv = CountVectorizer()

In [29]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [30]:
X_train_bow.shape

(7986, 48282)

**Using Naive Bayes**

In [31]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [32]:
y_pred = gnb.predict(X_test_bow)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [33]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]])

**Using Random Forest**

In [34]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8502754131196795

In [35]:
# increase the frequency
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8367551326990486

In [36]:
# increase the frequency using ngram
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8437656484727091

## **2. Tf-Idf**

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tfidf = TfidfVectorizer()

In [39]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

**Using Random Forest**

In [40]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8517776664997496

## **3. Word2Vec**

In [43]:
import numpy as np
import pandas as pd

In [44]:
temp_df = pd.read_csv('IMDB Dataset.csv')
df = temp_df.iloc[:10000]
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [45]:
df.drop_duplicates(inplace=True)

<ipython-input-45-16cdb8520be8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [47]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text
df['review'] = df['review'].apply(remove_tags)
df['review'] = df['review'].apply(lambda x:x.lower())

<ipython-input-47-455e4148a228>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)
<ipython-input-47-455e4148a228>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [48]:
from nltk.corpus import stopwords
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

<ipython-input-48-ad7e5e59762e>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [49]:
df['review']

0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production. filming technique...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy (jake) thi...
4       petter mattei's "love time money" visually stu...
                              ...                        
9995    fun, entertaining movie wwii german spy (julie...
9996    give break. anyone say "good hockey movie"? kn...
9997    movie bad movie. watching endless series bad h...
9998    movie probably made entertain middle school, e...
9999    smashing film film-making. shows intense stran...
Name: review, Length: 9983, dtype: object

In [50]:
import gensim
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [52]:
#sentence tokenize and pre-process
import nltk
nltk.download('punkt')
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

# model making
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

# build the vocabulary
model.build_vocab(story)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [53]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5874860, 6212140)

In [54]:
len(model.wv.index_to_key)

31845

In [55]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [56]:
document_vector(df['review'].values[0])

array([-0.21047199,  0.5523598 ,  0.2048741 ,  0.22141905, -0.121571  ,
       -0.62640965,  0.1901119 ,  0.98987544, -0.3683402 , -0.31470764,
       -0.23086748, -0.4611742 ,  0.09352009,  0.12833996,  0.2256626 ,
       -0.12752438, -0.03544987, -0.33480567, -0.08810337, -0.649585  ,
       -0.00449213,  0.18825752,  0.09669771, -0.27269894, -0.31269303,
       -0.00114886, -0.273058  ,  0.05752051, -0.29405382,  0.03709666,
        0.33589163, -0.00748485,  0.19733538, -0.26738474, -0.20289005,
        0.41739947,  0.12848909, -0.33312783, -0.25916758, -0.7792493 ,
        0.12148217, -0.1706192 ,  0.02832279, -0.12124948,  0.49518287,
       -0.15474059, -0.24717991, -0.02613189,  0.09549404,  0.32959613,
        0.03535578, -0.35344142, -0.4281744 , -0.1256826 , -0.11420976,
        0.2170138 ,  0.19527107,  0.02592436, -0.26255158,  0.08012518,
        0.04449997,  0.11679164,  0.04949323, -0.03934187, -0.41469735,
        0.23959382,  0.02519319,  0.1763024 , -0.35412496,  0.34

In [57]:
from tqdm import tqdm
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [08:28<00:00, 19.62it/s]


In [58]:
X = np.array(X)
X[0]

array([-0.21047199,  0.5523598 ,  0.2048741 ,  0.22141905, -0.121571  ,
       -0.62640965,  0.1901119 ,  0.98987544, -0.3683402 , -0.31470764,
       -0.23086748, -0.4611742 ,  0.09352009,  0.12833996,  0.2256626 ,
       -0.12752438, -0.03544987, -0.33480567, -0.08810337, -0.649585  ,
       -0.00449213,  0.18825752,  0.09669771, -0.27269894, -0.31269303,
       -0.00114886, -0.273058  ,  0.05752051, -0.29405382,  0.03709666,
        0.33589163, -0.00748485,  0.19733538, -0.26738474, -0.20289005,
        0.41739947,  0.12848909, -0.33312783, -0.25916758, -0.7792493 ,
        0.12148217, -0.1706192 ,  0.02832279, -0.12124948,  0.49518287,
       -0.15474059, -0.24717991, -0.02613189,  0.09549404,  0.32959613,
        0.03535578, -0.35344142, -0.4281744 , -0.1256826 , -0.11420976,
        0.2170138 ,  0.19527107,  0.02592436, -0.26255158,  0.08012518,
        0.04449997,  0.11679164,  0.04949323, -0.03934187, -0.41469735,
        0.23959382,  0.02519319,  0.1763024 , -0.35412496,  0.34

In [60]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])
y

array([1, 1, 1, ..., 0, 0, 1])

In [61]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [62]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [63]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7681522283425137